### ISSUE TITLE
Space character as a separator in the configuration

### ISSUE THREAD

**Issue by reff** [sliced-invoices/sliced-invoices#50] opened 2019-05-27 15:19 UTC
In the configuration of sliced invoice, there is a field for the thousand separator.  In french, the thousand separator is a space.  But when we add a space in that field, it crashes.
The non-breaking space is a temporary solution.
I'd rather call it a bug (a minor one though) since there should be a validation in the settings (IMHO).

**Comment by grantalltodavid** [comment] 2019-06-17 01:14
This issue was fixed in v3.7.0, more than a year ago. See 79c95e2f75fde9e73f47654e1908a7c255351a01

I think the user who reported this must be using an old version of Sliced Invoices.

**Comment by grantalltodavid** [comment] 2019-06-17 01:16
And just to confirm, I am not able to reproduce the issue.  The thousands separator will accept a space (" "), or even a non-breaking space ("&nbsp;") without any problems.

**Closed** 2019-06-17 01:16 UTC
Labels: invalid
