### ISSUE TITLE
Expired quotes remain expired after converting to invoice

### ISSUE THREAD

**Issue by nutsandbolts** [sliced-invoices/sliced-invoices#22] opened 2018-03-14 18:53 UTC
(iref 23942)

If a quote is expired and converted to an invoice after the expiration date, the quote disappears from the list and the count of expired quotes doesn't go down by 1. The invoice also isn't created. We need to add logic to un-expire it (for lack of a better word) if it's converted to an invoice later.

**Comment by grantalltodavid** [comment] 2018-03-19 08:34
I was able to reproduce the issue with the status count not going down.  When we convert the quote to invoice, we set the new invoice's status to "draft".  However we were not clearing the previous quote_status ("expired" or whatever, could be anything really).  Issue fixed via 5bb292d

I could not reproduce the other issue reported about invoices not being created.  That's working fine for me.

**Closed by grantalltodavid** 2018-03-19 08:34 UTC
Labels: bug
